export interface BoilerplateFile {
  path:    string
  content: string
}

/**
 * VIAN Mandatory Boilerplate
 * These files are planted into the WebContainer BEFORE the AI generation starts.
 * npm install runs in the background while AI streams files.
 * Dev server starts the moment AI delivers app/page.tsx.
 */
export const BOILERPLATE_FILES: BoilerplateFile[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'vian-app',
        version: '0.1.0',
        private: true,
        scripts: {
          dev:   'next dev',
          build: 'next build',
          start: 'next start',
          lint:  'next lint',
        },
        dependencies: {
          next:           '14.2.5',
          react:          '18.3.1',
          'react-dom':    '18.3.1',
          clsx:           '2.1.1',
          'lucide-react': '0.395.0',
        },
        devDependencies: {
          '@types/node':      '20.14.2',
          '@types/react':     '18.3.3',
          '@types/react-dom': '18.3.0',
          autoprefixer:       '10.4.19',
          postcss:            '8.4.38',
          tailwindcss:        '3.4.4',
          typescript:         '5.4.5',
        },
      },
      null,
      2,
    ),
  },

  {
    path: 'next.config.js',
    content: `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          { key: 'Cross-Origin-Embedder-Policy', value: 'require-corp' },
          { key: 'Cross-Origin-Opener-Policy',   value: 'same-origin'  },
        ],
      },
    ]
  },
}
module.exports = nextConfig`,
  },

  {
    path: 'tsconfig.json',
    content: JSON.stringify(
      {
        compilerOptions: {
          target:            'ES2017',
          lib:               ['dom', 'dom.iterable', 'esnext'],
          allowJs:           true,
          skipLibCheck:      true,
          strict:            true,
          noEmit:            true,
          esModuleInterop:   true,
          module:            'esnext',
          moduleResolution:  'bundler',
          resolveJsonModule: true,
          isolatedModules:   true,
          jsx:               'preserve',
          incremental:       true,
          plugins:           [{ name: 'next' }],
          paths:             { '@/*': ['./*'] },
        },
        include:  ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude:  ['node_modules'],
      },
      null,
      2,
    ),
  },

  {
    path: 'postcss.config.js',
    content: `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`,
  },

  {
    path: 'tailwind.config.ts',
    content: `import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: { extend: {} },
  plugins: [],
}

export default config`,
  },

  {
    path: 'app/globals.css',
    content: `@tailwind base;
@tailwind components;
@tailwind utilities;

* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }`,
  },

  {
    path: 'app/layout.tsx',
    content: `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by VIAN',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <script dangerouslySetInnerHTML={{ __html: \`
          window.onerror = function(msg, src, line, col, err) {
            window.parent && window.parent.postMessage({ type: 'preview-error', message: (err && err.message) || msg }, '*');
          };
          window.addEventListener('unhandledrejection', function(e) {
            window.parent && window.parent.postMessage({ type: 'preview-error', message: e.reason && e.reason.message ? e.reason.message : String(e.reason) }, '*');
          });
        \` }} />
      </head>
      <body>{children}</body>
    </html>
  )
}`,
  },

  {
    path: 'app/page.tsx',
    content: `export default function Page() {
  return (
    <main
      style={{
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: '#0a0a0a',
        flexDirection: 'column',
        gap: '12px',
      }}
    >
      <div
        style={{
          width: '8px',
          height: '8px',
          borderRadius: '50%',
          background: '#3b82f6',
          animation: 'pulse 1.4s ease-in-out infinite',
        }}
      />
      <p style={{ color: '#888888', fontSize: '13px', fontFamily: 'monospace' }}>
        Generating your app...
      </p>
      <style>{\`
        @keyframes pulse {
          0%, 100% { opacity: 1; transform: scale(1); }
          50% { opacity: 0.4; transform: scale(0.75); }
        }
      \`}</style>
    </main>
  )
}`,
  },

  {
    path: 'lib/utils.ts',
    content: `import { type ClassValue, clsx } from 'clsx'

export function cn(...inputs: ClassValue[]) {
  return clsx(inputs)
}

export function formatDate(date: string | Date): string {
  return new Intl.DateTimeFormat('en-US', {
    month: 'long',
    day:   'numeric',
    year:  'numeric',
  }).format(new Date(date))
}

export function slugify(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\\s-]/g, '')
    .replace(/\\s+/g, '-')
    .replace(/-+/g, '-')
}`,
  },
]
